version: "3"

services:
  hagencms-server:
    container_name: hagencms-server
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run start
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/bun/app/:rw,delegated
